{
 "title": "Data Sync",
 "tags": [ "data-sync" ],
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "content": "# Data Synchronization\n\nSync mobile data synchronization framework allows Sync Apps to seamessly continue working when the network conection is lost, and allows them to recover when the network connection is restored.\n\nFind out more at [docs.aerogear.org](https://docs.aerogear.org/aerogear/latest/data_sync.html)!"
  },
  {
   "title": "Number of Pods",
   "type": "singlestat",
   "description": "Number of currently provisioned Data Sync Server pods",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{datasync=\"yes\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nodejs_version_info{datasync=\"yes\"})"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Unique clients over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count( count by (client_id) (clients) )",
     "legendFormat": "Unique clients"
    }
   ]
  },
  {
   "title": "Unique users over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count( count by (user_id) (users) )",
     "legendFormat": "Unique users"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "description": "Memory currently being used by Data Sync Server pods",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{datasync=\"yes\"})"
    }
   ]
  },
  {
   "title": "Memory Usage In Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{datasync=\"yes\"})",
     "legendFormat": "Average of all pods"
    },
    {
     "expr": "process_resident_memory_bytes{datasync=\"yes\"}",
     "legendFormat": "Pod {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "description": "CPU currently being used by Data Sync Server.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(process_cpu_user_seconds_total{datasync=\"yes\"}[30s]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage In Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_user_seconds_total{datasync=\"yes\"}[30s]) * 100)",
     "legendFormat": "Average of all pods"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{datasync=\"yes\"}[30s]) * 100",
     "legendFormat": "Pod {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Queries/Mutations Resolved",
   "type": "graph",
   "description": "Number of queries and mutations resolved in time.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(requests_resolved{operation_type=\"query\", datasync=\"yes\"})",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(requests_resolved{operation_type=\"mutation\", datasync=\"yes\"})",
     "legendFormat": "Mutations"
    }
   ]
  },
  {
   "title": "Resolver Timings",
   "type": "graph",
   "description": "Resolver response time in milliseconds",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(resolver_timing_ms_sum{operation_type=\"query\", datasync=\"yes\"} / resolver_timing_ms_count{operation_type=\"query\", datasync=\"yes\"})",
     "legendFormat": "Query"
    },
    {
     "expr": "avg(resolver_timing_ms_sum{operation_type=\"mutation\", datasync=\"yes\"} / resolver_timing_ms_count{operation_type=\"mutation\", datasync=\"yes\"})",
     "legendFormat": "Mutation"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "graph",
   "description": "Server response time in milliseconds",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(server_response_ms_sum{request_type=\"POST\", datasync=\"yes\"} / server_response_ms_count{request_type=\"POST\", datasync=\"yes\"})",
     "legendFormat": "POST"
    },
    {
     "expr": "avg(server_response_ms_sum{request_type=\"GET\", datasync=\"yes\"} / server_response_ms_count{request_type=\"GET\", datasync=\"yes\"})",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Operations vs Conflicts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(requests_resolved{datasync=\"yes\"})",
     "legendFormat": "Operations"
    },
    {
     "expr": "sum(conflicts{datasync=\"yes\"})",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Conflicts over time per operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(conflicts{datasync=\"yes\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(conflicts{datasync=\"yes\"})",
     "legendFormat": "All Operations"
    }
   ]
  }
 ]
}